config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "projects#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :projects, only: [:index, :show, :new, :create, :update] do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :content, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  STATUSES = %w[Pending In\ Progress Review Completed Archived].freeze
  validates :status, inclusion: { in: STATUSES }
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_comment, only: :destroy
  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.new(
      comment_params.merge(user: current_user)
    )
    if @comment.save
      redirect_to @project, notice: "Comment was successfully added."
    else
      render "projects/show"
    end
  end

  def destroy
    if @comment.user == current_user
      @comment.destroy
      redirect_to @project, notice: "Comment was successfully deleted."
    else
      redirect_to @project, alert: "You can only delete your own comments."
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show update]

  def index
    @projects = Project.all.includes(:comments, :user)
  end

  def show; end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to projects_path, notice: "Project was successfully created."
    else
      flash.now[:alert] = "There was an error with your submission."
      render :new, alert: "Project could not be created. Name is required."
    end
  end

  def update
    if @project.user == current_user && @project.update(project_params)
      redirect_to @project, notice: "Status was successfully updated."
    else
      redirect_to @project, alert: "You are not authorized to update the status."
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:status, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectConversation</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.slim
.container.mt-5
  h1.text-center.mb-4.text-primary Projects

  .mt-4
  h2 Your Projects
  .row
    - @projects.where(user: current_user).each do |project|
      .col-md-6.col-lg-4.mb-4
        .card.shadow-sm
          .card-body
            h5.card-title = project.name
            p.card-text 
              strong Status: 
              span.badge-info.ml-2 = project.status
            p.text-muted
              strong Creator: 
              = project.user.name
            = link_to "View Details", project_path(project), class: "btn btn-outline-primary btn-sm mt-2"

  .mt-4
  = link_to "Create New Project", new_project_path, class: "btn btn-primary"

  .mt-4
  = button_to destroy_user_session_path, method: :delete, class: "btn btn-danger" do
    | Logout

  .mt-4
  h2 Other Users' Projects
  .row
    - @projects.where.not(user: current_user).each do |project|
      .col-md-6.col-lg-4.mb-4
        .card.shadow-sm
          .card-body
            h5.card-title = project.name
            p.card-text 
              strong Status: 
              span.badge-info.ml-2 = project.status
            p.text-muted
              strong Creator: 
              = project.user.name
            = link_to "View Details", project_path(project), class: "btn btn-outline-primary btn-sm mt-2"

app/views/projects/new.html.slim
.container.mt-5
  h1.text-center.mb-4.text-primary Create New Project

  - if @project.errors.any?
    .alert.alert-danger
      h4 Errors
      ul
        - @project.errors.full_messages.each do |msg|
          li= msg

  = form_with model: @project, url: projects_path, method: :post, local: true do |f|
    .form-group
      = f.label :name, "Project Name"
      = f.text_field :name, class: "form-control"
    
    .form-group
      = f.label :status, "Status"
      = f.select :status, Project::STATUSES, {}, { class: "form-control" }
    
    .form-group
      = f.submit "Create Project", class: "btn btn-success mt-3"

  = link_to "Back to Projects", projects_path, class: "btn btn-secondary mt-3"

app/views/projects/show.html.slim
.container.mt-4
  .card
    .card-body
      h1.card-title = @project.name
      p.card-text 
        strong Status: 
        span.badge-primary.ml-2 = @project.status

  p.text-muted
    strong Creator: 
    = @project.user.name

  - if @project.user == current_user
    .mt-4
    h2 Change Status
    = form_with model: @project, method: :patch, class: "form-inline" do |f|
      .form-group.mr-2
        = f.select :status, Project::STATUSES, {}, { class: "form-control" }
      = f.submit "Update", class: "btn btn-primary"

  .mt-4
  h2 Comments
  .list-group
    - @project.comments.each do |comment|
      .list-group-item
        strong = comment.user.name
        p.mb-0 = comment.content
        - if comment.user == current_user
          = button_to "Delete", project_comment_path(@project, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm ml-2"

  .mt-4
    h3 Add Comment
    = form_with model: [@project, Comment.new], class: "form-group" do |f|
      = f.hidden_field :user_id, value: current_user.id
      .form-group
        = f.text_area :content, class: "form-control", placeholder: "Write a comment..."
      = f.submit "Comment", class: "btn btn-success mt-2"

  .mt-4
    = link_to "Back to Projects", projects_path, class: "btn btn-secondary"